version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
